# Generated by Django 3.2.13 on 2022-06-10 11:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import livefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', livefield.fields.LiveField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Bundle Set - Name')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundleset_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
            ],
            options={
                'verbose_name': 'Bundle Set',
                'verbose_name_plural': 'Bundle Sets',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', livefield.fields.LiveField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('sku_code', models.CharField(max_length=20, verbose_name='SKU Code')),
                ('lagacy_sku', models.CharField(default='', max_length=20, verbose_name='Lagacy SKU')),
                ('tax', models.PositiveSmallIntegerField(choices=[(1, 'Exclude Vat'), (2, 'Include VAT 7%')], default=1, verbose_name='Tax')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Unpublished')], default=1, verbose_name='Status')),
                ('product_type', models.PositiveSmallIntegerField(choices=[(1, 'Course'), (2, 'Course Bundle'), (3, 'Course Book'), (4, 'Course Service'), (5, 'EduGadget'), (6, 'EduGadget Bundle'), (7, 'Simulation Test'), (8, 'E-Document'), (9, 'Course EduGadget'), (10, 'Packaging'), (11, 'External course'), (12, 'External Exam'), (13, 'Facebook Private Group'), (14, 'Support Sale'), (15, 'Gift')], default=1, verbose_name='Product Type')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product_groups.productgroup', verbose_name='Product Group')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Edited User')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', livefield.fields.LiveField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('alt_image', models.CharField(max_length=255, verbose_name='Alt. Image')),
                ('display_type', models.PositiveSmallIntegerField(choices=[(1, 'Mobile'), (2, 'Desktop'), (3, 'Tablet')], default=2)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimage_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Product')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimage_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Edited User')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='BundleSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', livefield.fields.LiveField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5, verbose_name='Quantity')),
                ('bundle_set', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.bundleset', verbose_name='Bundle Set')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundlesetitem_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('product', models.ForeignKey(limit_choices_to={'product_type__in': [1, 3, 4, 5, 7, 8, 9, 11, 12, 13]}, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Product')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product_groups.productgroup', verbose_name='Product Group')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundlesetitem_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Edited User')),
            ],
            options={
                'verbose_name': 'Bundle Set - Item',
                'verbose_name_plural': 'Bundle Set - Items',
                'ordering': ('pk',),
                'unique_together': {('bundle_set', 'product', 'live')},
            },
        ),
        migrations.AddField(
            model_name='bundleset',
            name='items',
            field=models.ManyToManyField(related_name='items', through='products.BundleSetItem', to='products.Product', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='bundleset',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type__in': [1, 3, 4, 5, 7, 8, 9, 11, 12, 13]}, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='bundleset',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundleset_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Edited User'),
        ),
        migrations.AlterUniqueTogether(
            name='bundleset',
            unique_together={('name', 'product', 'live')},
        ),
    ]
