# Generated by Django 3.2.13 on 2022-06-10 11:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import livefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', livefield.fields.LiveField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5, verbose_name='cost')),
                ('mms_timestamp', models.DateTimeField(verbose_name='MMS Timestamp')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcost_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Product')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcost_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Edited User')),
            ],
            options={
                'verbose_name': 'Product Cost',
                'verbose_name_plural': 'Product Costs',
                'ordering': ('pk',),
                'unique_together': {('product', 'mms_timestamp', 'cost', 'live')},
            },
        ),
    ]
