# Generated by Django 3.2.13 on 2022-06-10 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import livefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', livefield.fields.LiveField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='Group name')),
                ('lms_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='LMS ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productgroup_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productgroup_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Edited User')),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
                'ordering': ('pk',),
                'unique_together': {('slug', 'live')},
            },
        ),
    ]
